# Generated by Django 4.2.7 on 2023-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('edad', models.IntegerField()),
                ('numero', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacionescomentarios',
            fields=[
                ('id_calificacioncomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('fecha_calificacioncomentario', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacionescomentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosTransaccion',
            fields=[
                ('id_estado_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estados_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocacionPaseador',
            fields=[
                ('id_locacion_paseador', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=38, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=38, null=True)),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locacion_paseador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocacionPropietario',
            fields=[
                ('id_locacion_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=38, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=38, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locacion_propietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('necesidades', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paseadores',
            fields=[
                ('id_paseador', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibilidad', models.IntegerField()),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paseadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paseos',
            fields=[
                ('id_paseo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_paseo', models.DateTimeField(blank=True, null=True)),
                ('duracion_real', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=25, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paseos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('preferencias_paseo', models.TextField(blank=True, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibilidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=20)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propietarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('duracion_paseo', models.TimeField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('punto_encuentro', models.CharField(blank=True, max_length=25, null=True)),
                ('lugar_paseo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposMascota',
            fields=[
                ('id_tipo_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposTransaccion',
            fields=[
                ('id_tipo_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('apodo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=35)),
                ('edad', models.PositiveIntegerField()),
                ('celular', models.CharField(max_length=9, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('estado', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
